### ISSUE TITLE
Optimize Screenshots

### ISSUE THREAD

**Issue by andrewdmaclean** [hightechu/portfolio#17]
The screenshots for projects( as displayed in the repo card) from the Summer 2020 Academy need to be optimized to the same standard as the previously completed projects.

The projects in question are as follows:

- https://github.com/hightechu/portfolio/blob/master/assets/img/hightechu-academy-bubblet.png
- https://github.com/hightechu/portfolio/blob/master/assets/img/hightechu-academy-effortlessdistancing.png
- https://github.com/hightechu/portfolio/blob/master/assets/img/hightechu-academy-forestfiredetector.png
- https://github.com/hightechu/portfolio/blob/master/assets/img/hightechu-academy-radbag.png

**Comment by FlyteWizard** [comment]
@andrewdmaclean Is this what you want?

![hightechu-academy-forestfiredetector](https://user-images.githubusercontent.com/10472448/92798035-76e32480-f367-11ea-97d1-6518a8096765.png)

**Comment by andrewdmaclean** [comment]
@FlyteWizard that is it :) I just made a few changes to the Repo descriptions so if you are able to regenerate the screenshots that would be awesome!

**Comment by andrewdmaclean** [comment]
@FlyteWizard I am done

**Comment by FlyteWizard** [comment]
@andrewdmaclean The GitHub Pages aren't being updated.

**Comment by FlyteWizard** [comment]
@andrewdmaclean Is it okay that the screenshot has the old description. The GitHub Pages won't update without a new push.

**Comment by andrewdmaclean** [comment]
@FlyteWizard that's fine

**Comment by FlyteWizard** [comment]
@andrewdmaclean The PR is ready for review.
